Repository QOSQOs/UNIVeasier, pull requests merged in 2019-10, with the labels that each got.

#10 fix: enhance the layout of the project
  build/build.md
  cmd/uknow.go
  docs/layoutProject.md
  examples/install.md
  examples/main.go
  internal/UI/mock.html
  internal/UI/mock.js
  internal/configs/conf.json
  pkg/api/universityRoute.go
  pkg/api/universityRoute_test.go
  pkg/app/universityService.go
  pkg/app/universityService_test.go
  pkg/db/universityDao.go
  pkg/db/universityDao_test.go
  pkg/model/university/universityModel.go
  pkg/model/university/universityModel_test.go
  test/test.md
  third_party/third_party.md
  vendor/vendor.md
Labels: design

#16 fix: add CORS - Cross Origin Resource Sharing
  examples/main.go
Labels: example

#14 feat: add the first version of the model layer
  pkg/model/activity/commentModel.go
  pkg/model/activity/commentModel_test.go
  pkg/model/activity/contributionModel.go
  pkg/model/activity/contributionModel_test.go
  pkg/model/activity/enrollmentModel.go
  pkg/model/activity/enrollmentModel_test.go
  pkg/model/career/careerModel.go
  pkg/model/career/careerModel_test.go
  pkg/model/complement/albumModel.go
  pkg/model/complement/albumModel_test.go
  pkg/model/complement/awardModel.go
  pkg/model/complement/awardModel_test.go
  pkg/model/complement/interestModel.go
  pkg/model/complement/interestModel_test.go
  pkg/model/complement/photoModel.go
  pkg/model/complement/photoModel_test.go
  pkg/model/complement/scheduleModel.go
  pkg/model/complement/scheduleModel_test.go
  pkg/model/complement/storyMode_test.go
  pkg/model/complement/storyModel.go
  pkg/model/complement/tagContainerModel.go
  pkg/model/complement/tagContainerModel_test.go
  pkg/model/course/courseConnectionModel.go
  pkg/model/course/courseConnectionModel_test.go
  pkg/model/course/courseModel.go
  pkg/model/course/courseModel_test.go
  pkg/model/course/typeCourseModel.go
  pkg/model/course/typeCourseModel_test.go
  pkg/model/faculty/facultyModel.go
  pkg/model/faculty/facultyModel_test.go
  pkg/model/person/careerPersonModel.go
  pkg/model/person/careerPersonModel_test.go
  pkg/model/person/personModel.go
  pkg/model/person/personModel_test.go
  pkg/model/university/typeUniversityModel.go
  pkg/model/university/typeUniversityModel_test.go
  pkg/model/university/universityModel.go
Labels: design

#15 feat: add database script
  docs/class_diagram.mwb
  docs/database.md
  internal/UI/mock.html
  internal/UI/mock.js
  internal/scripts/dbqosqos.sql
Labels: design

#19 fix: improve the database script
  internal/scripts/dbqosqos.sql
Labels: design

#18 fix: improve classes diagram
  docs/class_diagram.mwb
Labels: fix

#17 feat: add example of the connection database class
  examples/config.go
  examples/config.json
  examples/connection.go
  examples/main.go
Labels: example

#21 fix: enhance the model based on the recent changes done in the database
  docs/database.md
  pkg/model/activity/commentModel.go
  pkg/model/activity/contributionModel.go
  pkg/model/complement/awardModel.go
  pkg/model/complement/interestModel.go
  pkg/model/complement/storyModel.go
  pkg/model/complement/tagContainerModel.go
  pkg/model/course/typeCourseModel.go
  pkg/model/university/universityModel.go
Labels: fix

#23 fix: add dummy data and fix files of the model based on the changes made on the DB
  docs/class_diagram.mwb
  docs/database.md
  internal/scripts/databases/dbqosqos.sql
  internal/scripts/databases/dbtest.sql
  internal/scripts/dummy_data/dbqosqos.sql
  internal/scripts/dummy_data/dbtest.sql
  pkg/model/activity/commentModel.go
  pkg/model/activity/contributionModel.go
  pkg/model/activity/enrollmentModel.go
  pkg/model/complement/albumModel.go
  pkg/model/complement/awardModel.go
  pkg/model/complement/interestModel.go
  pkg/model/complement/photoModel.go
  pkg/model/complement/scheduleModel.go
  pkg/model/complement/storyModel.go
  pkg/model/complement/tagContainerModel.go
  pkg/model/course/courseConnectionModel.go
  pkg/model/course/courseModel.go
  pkg/model/course/typeCourseModel.go
  pkg/model/person/careerPersonModel.go
  pkg/model/person/personModel.go
  pkg/model/university/careerModel.go
  pkg/model/university/facultyModel.go
  pkg/model/university/typeUniversityModel.go
  pkg/model/university/universityModel.go
Labels: fix

#24 doc: add development setup document
  docs/devSetup.md
  examples/examples.md
  examples/install.md
  internal/scripts/dummy_data/dbtest.sql
  internal/scripts/procedures/test.sql
Labels: documentation

#28 fix: improve way to reference configuration file
  cmd/univeasier.go
  internal/config/config.json
Labels: fix

#29 fix: order of the environment variables
  docs/devSetup.md
Labels: fix

#30 feat: add insert operation to model test
  internal/scripts/procedures/test.sql
  pkg/api/testRoute.go
  pkg/app/testService.go
  pkg/db/testDao.go
Labels: example

#33 feat: add the initial procedures SQL (insert, update, get and list)
  docs/class_diagram.mwb
  internal/scripts/databases/dbqosqos.sql
  internal/scripts/procedures/dbqosqos/album.sql
  internal/scripts/procedures/dbqosqos/award.sql
  internal/scripts/procedures/dbqosqos/career.sql
  internal/scripts/procedures/dbqosqos/careerPerson.sql
  internal/scripts/procedures/dbqosqos/comment.sql
  internal/scripts/procedures/dbqosqos/contribution.sql
  internal/scripts/procedures/dbqosqos/course.sql
  internal/scripts/procedures/dbqosqos/coursesConnection.sql
  internal/scripts/procedures/dbqosqos/enrollment.sql
  internal/scripts/procedures/dbqosqos/faculty.sql
  internal/scripts/procedures/dbqosqos/interest.sql
  internal/scripts/procedures/dbqosqos/person.sql
  internal/scripts/procedures/dbqosqos/photo.sql
  internal/scripts/procedures/dbqosqos/schedule.sql
  internal/scripts/procedures/dbqosqos/story.sql
  internal/scripts/procedures/dbqosqos/tagContainer.sql
  internal/scripts/procedures/dbqosqos/typeCourse.sql
  internal/scripts/procedures/dbqosqos/typeUniversity.sql
  internal/scripts/procedures/dbqosqos/university.sql
Labels: feature
